### ISSUE TITLE
ENH: Update Semantic Type for Diamond DB

### ISSUE THREAD

**Issue by Sann5** [bokulich-lab/q2-types-genomics#64]
### Problem and solution
There is a need to update the Semantic type of diamond DB, according to this issue: bokulich-lab/q2-moshpit#97

As of now the semantic type looks like this [q2-types-genomics/blob/main/q2_types_genomics/reference_db/_format.py](https://github.com/bokulich-lab/q2-types-genomics/blob/6aa91a46ef54784269ccb270f78208b31f859dfd/q2_types_genomics/reference_db/_format.py#L45)

```python
45 DiamondDatabaseDirFmt = model.SingleFileDirectoryFormat(
46   'DiamondDatabaseDirFmt', 'ref_db.dmnd', DiamondDatabaseFileFmt)
```

It is essentially a directory with one file named `ref_db.dmnd`. The update needs to accommodate the fact that now there can be multiple files. E.g.

```
e5.proteomes.faa
e5.taxid_info.tsv
Archaea.dmnd
Bacteria.dmnd
```

See the issue linked above for explanations of what these files are. 

### Additional Considerations
- Care should be taken that the output artifact can be accessed in the downstream actions.

**Comment by misialq** [comment]
Hey @Sann5, I'm pretty sure that you only need the `*.dmnd` files but not the other ones - they are used to build the Diamond database so once you got the dmnd files, you can remove the other ones.

**Comment by Sann5** [comment]
After taking into account the way the artifact is accessed in the downstream action (`eggnog_diamond_search`), we have opted to leave the Semantic type as is.
