### ISSUE TITLE
ENH: Update `NCBITaxonomyDirFmt` to accomodate data-version file

### ISSUE THREAD

**Issue by Sann5** [bokulich-lab/q2-types-genomics#72]
- An `fetch-ncbi-taxonomy-data` action is planned (bokulich-lab/q2-moshpit#107)
- This will download data from two different sources. Consequently, there is a need to add version information to the resulting artifact.
- This information will be written to an additional file within the artifact, provisionally `version.tsv`.
- Consequently, there is a need to modify the code in `NCBITaxonomyDirFmt` to accommodate this extra file. 
- Validation for the extra file should also be implemented. 
- Test suit should be adjusted/expanded accordingly.

**Comment by misialq** [comment]
Hey @Sann5, do we still need this or can it be closed?

**Comment by Sann5** [comment]
@misialq pps I closed the PR but not the issue. Sorry. I close it now.
